version: '3'
services:
  chat-db:
    build:
      context: ./DATABASE/CASSANDRA
      dockerfile: Dockerfile
    container_name: chat-db
    volumes:
      - ./DATABASE/CASSANDRA/entrypoint.sh:/docker-entrypoint-initdb.d/docker-entrypoint.sh
      - ./DATABASE/CASSANDRA/schema.cql:/docker-entrypoint-initdb.d/schema.cql
    ports:
      - "9043:9042"
    networks:
      - desire

  chat-service:
    build: ./
    image: chat-service
    container_name: chat-service
    environment:
      SPRING_APPLICATION_NAME: chat-service
      SPRING_DATASOURCE_URL: jdbc:mysql://chat-db:3306/chatdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
      SPRING_PROFILES_ACTIVE: prod

      CASSANDRA_USERNAME: cassandra
      CASSANDRA_PASSWORD: cassandra
      CASSANDRA_CONTACT_POINT: chat-db
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: chatdb
      CASSANDRA_LOCAL_DC: datacenter1
      SERVICE_REGISTRY_URL: http://service-registry:8761/eureka
    ports:
      - "5002:8080"
    depends_on:
      - chat-db
    networks:
      - desire

networks:
  desire:
    external: true